site_name: PurrBot Documentation
site_description: 'API-Documentation and Wiki of *Purr*'
site_author: 'Andre_601'

site_url: 'https://docs.purrbot.site'

copyright: |
  Docs made with 
  <img alt="❤" class="twemoji heart-anim md-footer-custom-text" src="https://twemoji.maxcdn.com/v/latest/svg/2764.svg" title="love"> 
  and available under the 
  <a href="https://github.com/purrbot-site/Docs/blob/master/LICENSE" target="_blank" rel="nofollow">MIT-License</a>.

docs_dir: docs/

repo_name: purrbot-site/PurrBot
repo_url: https://github.com/purrbot-site/PurrBot
edit_uri: https://github.com/purrbot-site/Docs/edit/master/docs

nav:
  - index.md
  - API:
    - api/index.md
  - Bot:
    - bot/index.md
    - bot/commands.md
    - bot/faq.md
    - bot/selfhosting.md
    - Welcome-System:
      - bot/welcome-channel.md
      - bot/welcome-images.md
  - Contributing:
    - contribute/index.md
    - contribute/formatting-help.md
    - Translations:
      - contribute/translate/index.md
      - contribute/translate/translate-docs.md
  - credits/index.md
  - Legal: 
    - legal/index.md
    - legal/bot.md
    - legal/api.md
    - legal/website.md

theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: octicons/sun-24
        name: "Switch to Dark Mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: blue
      toggle:
        icon: octicons/moon-24
        name: "Switch to Light Mode"
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - content.code.annotate
  icon:
    repo: fontawesome/brands/square-github
    admonition:
      note: octicons/pencil-16
      abstract: octicons/multi-select-16
      info: octicons/info-16
      tip: octicons/rocket-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/stop-16
      failure: octicons/x-circle-16
      danger: octicons/alert-16
      bug: octicons/bug-16
      example: octicons/list-unordered-16
      quote: octicons/comment-16

watch:
  - theme

extra_css:
  - 'assets/css/extra.css'

extra:
  social:
    - icon: 'simple/patreon'
      link: 'https://patreon.com/andre_601'
    - icon: 'simple/github'
      link: 'https://github.com/purrbot-site'
    - icon: 'simple/twitter'
      link: 'https://twitter.com/TruePurrBot'
    - icon: 'simple/mastodon'
      link: 'https://botsin.space/@purrbot'
  translate:
    missing_translation: 'This page has not yet been translated.'
    not_translatable: 'This page cannot be translated and is therefore only available in English.'
    footer: |
      Build using <a href="https://www.mkdocs.org" target="_blank" rel="noopener">MkDocs</a>,
      <a href="https://squidfunk.github.io/mkdocs-material" target="_blank" rel="noopener">Material for MkDocs</a> and
      <a href="https://facelessuser.github.io/pymdown-extensions/" target="_blank" rel="noopener">Pymdown Extensions</a>.

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de_CH
          name: Deutsch (Schweiz)
          build: true
          site_name: PurrBot Dokumentation
          site_description: 'API-Dokumentation und Wiki von *Purr*'
          copyright: |
            Dokumentation mit 
            <img alt="❤" class="twemoji heart-anim md-footer-custom-text" src="https://twemoji.maxcdn.com/v/latest/svg/2764.svg" title="Liebe"> 
            gemacht und unter der
            <a href="https://github.com/purrbot-site/Docs/blob/master/LICENSE" target="_blank" rel="nofollow">MIT-Lizenz</a> verfügbar.
          extra:
            translate:
              missing_translation: 'Diese Seite wurde noch nicht übersetzt.'
              not_translatable: 'Diese Seite kann nicht übersetzt werden und ist darum nur auf Englisch verfügbar.'
              footer: |
                Erstellt mit <a href="https://www.mkdocs.org" target="_blank" rel="noopener">MkDocs</a>,
                <a href="https://squidfunk.github.io/mkdocs-material" target="_blank" rel="noopener">Material for MkDocs</a> und
                <a href="https://facelessuser.github.io/pymdown-extensions/" target="_blank" rel="noopener">Pymdown Extensions</a>.
          nav_translations:
            # Welcome system
            Welcome-System: Willkommenssystem
            # Contributing
            Contributing: Mitmachen
            Translations: Übersetzungen
            # Legal
            Legal: Rechtliches

hooks:
  - theme/.hooks/badges.py
  - theme/.hooks/theme_overrides_manager.py
  - theme/.hooks/language_flags.py

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - meta
  - pymdownx.superfences
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path:
        - theme/.snippets
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: true
