site_name: PurrBot Documentation
site_description: 'API-Documentation and Wiki of *Purr*'
site_author: 'Andre_601'

site_url: 'https://docs.purrbot.site'

copyright: |
  Docs made with 
  <img alt="❤" class="twemoji heart-anim md-footer-custom-text" src="https://twemoji.maxcdn.com/v/latest/svg/2764.svg" title="love"> 
  and provided under the 
  <a href="https://github.com/purrbot-site/Docs/blob/master/LICENSE" target="_blank">MIT-License</a>.

docs_dir: docs/

repo_name: purrbot-site/PurrBot
repo_url: https://github.com/purrbot-site/PurrBot
edit_uri: https://github.com/purrbot-site/Docs/edit/master/docs

nav:
  - Welcome: index.md
  - API:
    - api/index.md
  - Bot:
    - General:
      - bot/index.md
      - Commands: bot/commands.md
      - FAQ: 'https://purrbot.site/discord'
      - Selfhosting: bot/selfhosting.md
    - Welcome-System:
      - Setup: bot/welcome-channel.md
      - Images: bot/welcome-images.md
  - Contributing:
    - contribute/index.md
    - Formatting Help: contribute/formatting-help.md
    - Translations: contribute/translate.md
  - Credits:
    - credits/index.md
  - Legal: 
    - legal/index.md
    - Bot: legal/bot.md
    - API: legal/api.md
    - Website: legal/website.md

theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: blue
      toggle:
        icon: octicons/sun-24
        name: "Switch to Dark Mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: blue
      toggle:
        icon: octicons/moon-24
        name: "Switch to Light Mode"
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.top
  - content.code.annotate
  icon:
    repo: fontawesome/brands/square-github
    admonition:
      note: octicons/pencil-16
      abstract: octicons/multi-select-16
      info: octicons/info-16
      tip: octicons/rocket-16
      success: octicons/check-circle-16
      question: octicons/question-16
      warning: octicons/stop-16
      failure: octicons/x-circle-16
      danger: octicons/alert-16
      bug: octicons/bug-16
      example: octicons/list-unordered-16
      quote: octicons/comment-16

watch:
  - .snippets
  - theme

extra_css:
  - 'assets/css/extra.css'

extra:
  social:
    - icon: 'simple/patreon'
      link: 'https://patreon.com/andre_601'
    - icon: 'simple/github'
      link: 'https://github.com/purrbot-site'
    - icon: 'simple/twitter'
      link: 'https://twitter.com/TruePurrBot'
    - icon: 'simple/mastodon'
      link: 'https://botsin.space/@purrbot'

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  #- swagger-ui-tag:
  #    tryItOutEnabled: false
  #    supportedSubmitMethods: []
  #    extra_css:
  #      - assets/css/styling/swagger.css

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - meta
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path:
        - .snippets
