name: Pull request Deploy preview

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/**'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/find-comment@v2
        id: find-comment
        name: Find Comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: gh-pages-deploy
      - uses: peter-evans/create-or-update-comment@v4
        name: Create Comment
        with:
          body: |-
            ## Deploy Preview
            
            Skipping Deploy Preview.
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.BOT }}
          edit-mode: replace
